---
title: 异常处理
date: 2023-02-04 15:47:07
permalink: /pages/836a39/
categories:
  - Java基础
tags:
  - 
---
# 异常处理

***

## 1、异常的概念

异常是阻止当前方法或作用域继续执行的问题， 在程序中导致程序中断运行的一些指令。  

![image-20211016201000680](https://typora001-zc.oss-cn-chengdu.aliyuncs.com/typoraImg/image-20211016201000680.png)

***

## 2、异常处理

### 2.1、try与catch关键字

在程序中出现异常， 就必须进行处理， 处理格式如下：

```java
try(….) { //JDK1.7以后直接释放资源
	// 有可能发生异常的代码段
}catch(异常类型 对象){
	// 异常的处理操作
}catch(异常类型 对象){
	// 异常的处理操作
} ...
finally{
	// 异常的统一出口
}  
```

### 2.2、异常处理过程分析

1. 一旦产生异常， 则系统会自动产生一个异常类的实例化对象。
2. 此时如果存在了try语句， 则会自动找到匹配的catch语句执行， 如果没有异常处理， 则程序将退出， 并由系统报告错误。
3. 所有的catch根据方法的参数匹配异常类的实例化对象， 如果匹配成功， 则表示由此catch进行处理。  

### 2.3、finally关键字

在进行异常的处理之后， 在异常的处理格式中还有一个finally语句， 那么此语句将作为异常的统一出口， 不管是否产生了异常， 最终都要执行此段代码  

### 2.4、throw与throws关键字

1. throws关键字主要在方法的声明上使用， 表示方法中不处理异常， 而交给调用处处理。实际上对于Java程序来讲，如果没有加入任何的异常处理，默认由JVM进行异常的处理操作。
2. throw关键字表示在程序中手动抛出一个异常，因为从异常处理机制来看，所有的异常一旦产生之后，实际上抛出的就是一个异常类的实例化对象，那么此对象也可以由throw直接抛出。  

throws与throw常配合使用

throw后会跳出方法，所以在后面不需要写return

```java
private static int div2(int a, int b) throws ArithmeticException {
		try {
			int c = a / b;
			return c;
		} catch (ArithmeticException e) {
			throw new ArithmeticException("除数不能为零");	//带参的构造方法
		} finally {
			System.out.println("运行结束");
		}
	}
```

### 2.5、异常处理的语法规则

1. try语句不能单独存在， 可以和catch、 finally组成 try...catch...finally、try...catch、 try...finally三种结构， catch语句可以有一个或多个， finally语句最多一个，try、 catch、 finally这三个关键字均不能单独使用。
2. try、 catch、 finally三个代码块中变量的作用域分别独立而不能相互访问。
3. 多个catch块时候， Java虚拟机会匹配其中一个异常类或其子类， 就执行这个catch块， 而不会再执行别的catch块。  

## 3、 自定义异常  

在Java中， 已经提供了很多的异常类的定义， 但是我们在实际项目开发中， 可能需要使用一些自己的异常类， 那么可以通过继承Exception类或已有的异常类的方式完成一个自定义异常类的操作。

- ClassNotFoundException
- DataFormatException
- RuntimeException
- ArithmeticException
- IndexOutOfBoundsException
- NullPointerException
- ClassCastException

- ArrayIndexOutOfBoundsException
- InputMismatchException
- Exception
- …… 

**自定义异常的实现，通常是提供构造方法**

### 3.1、MyException

```java
/**
 * 自定义异常通常都是通过继承一个异常类来实现
 * 1、Throwable
 * 2、Exception
 * 3、RuntimeException
 * 
 * 自定义异常常的实现是，提供构造方法
 * 异常对象本身是没有实际功能，只是一个有意义的标识
 */
public class MyException extends RuntimeException{
	public MyException(){
		super();
	}
	public MyException(String message){
		super(message);
	}
}

```

### 3.2、UserService

```java
public class UserService {

	public User login(String username,String password)throws MyException{
		
		if(!"admin".equals(username)){
			throw new MyException("用户名错误");
		}
		if(!"12345".equals(password)){
			throw new MyException("密码错误");
		}
		User user = new User("admin","12345",18,"男");
		return user;
	}
}
```

***

## 4、 受检与非受检异常  

**受检异常： Exception**

定义方法时必须声明所有可能会抛出的exception； 在调用这个方法时， 必须捕获它的checked exception， 不然就得把它的exception传递下去； exception是从java.lang.Exception类衍生出来的。 例如： IOException， SQLException就属于Exception

**非受检异常： RuntimeException**

在定义方法时不需要声明会抛出runtime exception； 在调用这个方法时不需要捕获这个runtime exception； runtime exception是从java.lang.RuntimeException或java.lang.Error类衍生出来的。 例如： NullPointException，IndexOutOfBoundsException就属于runtime exception  

```java
//面试题 ：
// Exception 与 RuntimeException
// Exception:受检异常，在编程期检查，在调用抛出这个异常的方法时，必须显示的使用try...catch...
// RuntimeException:非受检异常，在运行期检查，在调用抛出这个异常的方法时，可以不用显示的使用try...catch...
// 在使用自定义异常时，根据实际的业务要求，来决定使用哪个作为父类
```

**assert关键字， 表示断言**

当程序执行到某个固定位置的时候， 程序中的某个变量的取值肯定是预期的结果， 那么这种操作可以使用断言完成。

断言的操作语法：assert 表达式 ;  

```java
public class AssertDemo {

	public static void main(String[] args) {

		int result = add(10,10);
		assert result==20:"结果不正确";
	}
	
	private static int add(int a,int b){
		return a+b+1;
	}

}
```

